
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main

    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://172.16.12.85:11434
    volumes:
      - open-webui-data:/app/backend/data
    networks:
      bridge-net:
        ipv4_address: 172.28.0.10

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-open-ui
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiMmRkNjk4MmZjYzE4ZDY5N2M3YWUzNDdkMWM4MjgwMjAiLCJ0IjoiMDg1ZjA3MTktYjA5Yy00N2VkLTkwNGItMTIzYjUzMTUwYzdjIiwicyI6Ik1qSTFabUkyWVRFdE1ERTVZeTAwT1dJNUxUaGtaakl0WlRGbVpUVXhNalppTVRaayJ9
    networks:
      bridge-net:
        ipv4_address: 172.28.0.11

volumes:
  open-webui-data:

networks:
  bridge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1
